[phases.setup]
nixPkgs = ["ffmpeg", "python312"]
cmd = "python3.12 -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"

[phases.build]
cmd = "cp -r /opt/venv ."

[start]
cmd = "python3.12 main.py"
